# Generated by Django 6.1.1 on 2026-09-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Mẹo từ local (ngắn gọn, thiết thực, món nên thử, giờ vắng...)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Mẹo địa phương',
                'verbose_name_plural': 'Danh sách mẹo',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên địa điểm')),
                ('category', models.CharField(choices=[('EAT_DRINK', 'Ăn uống'), ('PLAY', 'Vui chơi'), ('SERVICES', 'Dịch vụ')], db_index=True, max_length=50, verbose_name='Danh mục')),
                ('district', models.CharField(db_index=True, default='Thủ Đức', max_length=100, verbose_name='Quận/Khu vực')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ (Lat)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ (Lng)')),
                ('cover_image', models.URLField(blank=True, default='', max_length=1000, verbose_name='Link ảnh bìa')),
                ('verified_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Số lượng local xác thực')),
                ('trust_tier', models.PositiveSmallIntegerField(choices=[(0, 'Chưa có xác thực local'), (1, '1-2 local xác thực (icon check)'), (2, '3+ local xác thực (hiển thị số)')], db_index=True, default=0, verbose_name='Huy hiệu tín nhiệm')),
                ('last_verified_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xác thực gần nhất')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Địa điểm',
                'verbose_name_plural': 'Danh sách địa điểm',
                'ordering': ['-verified_count', '-last_verified_at', '-id'],
                'indexes': [models.Index(fields=['district', 'category', '-verified_count'], name='place_dist_cat_ver_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian xác thực')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='places.place', verbose_name='Địa điểm')),
            ],
            options={
                'verbose_name': 'Lượt xác thực local',
                'verbose_name_plural': 'Danh sách lượt xác thực',
            },
        ),
    ]
