# Generated by Django 6.1.1 on 2026-09-25 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placeverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Cư dân xác thực'),
        ),
        migrations.AddField(
            model_name='tip',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='places.place', verbose_name='Địa điểm'),
        ),
        migrations.AddField(
            model_name='tip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả'),
        ),
        migrations.AddConstraint(
            model_name='placeverification',
            constraint=models.UniqueConstraint(fields=('place', 'user'), name='unique_user_place_verification'),
        ),
        migrations.AddConstraint(
            model_name='tip',
            constraint=models.UniqueConstraint(fields=('place', 'user'), name='unique_user_place_tip'),
        ),
    ]
