# Generated by Django 6.1.1 on 2026-09-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_maps_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Link Google Maps gốc'),
        ),
        migrations.AddField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Google Place ID'),
        ),
        migrations.AddField(
            model_name='place',
            name='google_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Điểm Google Maps'),
        ),
        migrations.AddField(
            model_name='place',
            name='google_review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng review trên Google'),
        ),
        migrations.AddField(
            model_name='place',
            name='google_reviews',
            field=models.JSONField(blank=True, default=list, verbose_name='Review từ Google (Dữ liệu thô tham khảo)'),
        ),
        migrations.AddField(
            model_name='place',
            name='google_scraped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm thu thập từ Google'),
        ),
    ]
