# Generated by Django 6.1.1 on 2026-09-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_google_maps_url_place_google_place_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='imported_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Thời điểm nhập vào HubLocal'),
        ),
    ]
