# Generated by Django 6.1.1 on 2026-09-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_imported_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='data_source',
            field=models.CharField(default='google_maps', max_length=50, verbose_name='Nguồn dữ liệu gốc'),
        ),
        migrations.AddField(
            model_name='place',
            name='district_code',
            field=models.CharField(db_index=True, default='THU_DUC', max_length=50, verbose_name='Mã quận chuẩn hóa'),
        ),
        migrations.AddField(
            model_name='place',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá tối đa (VNĐ)'),
        ),
        migrations.AddField(
            model_name='place',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá tối thiểu (VNĐ)'),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours_structured',
            field=models.JSONField(blank=True, default=dict, verbose_name='Cấu trúc giờ mở cửa tuần'),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Giờ mở cửa hiển thị'),
        ),
        migrations.AddField(
            model_name='place',
            name='price_currency',
            field=models.CharField(default='VND', max_length=10, verbose_name='Đơn vị tiền tệ'),
        ),
        migrations.AddField(
            model_name='place',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm cập nhật giá'),
        ),
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Đang hoạt động'), ('TEMP_CLOSED', 'Tạm thời đóng cửa'), ('PERM_CLOSED', 'Đã ngừng hoạt động')], db_index=True, default='OPEN', max_length=20, verbose_name='Trạng thái hoạt động'),
        ),
        migrations.AddField(
            model_name='place',
            name='thumbnail_image',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Link ảnh thu nhỏ'),
        ),
        migrations.CreateModel(
            name='PlaceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('CLOSED', 'Quán đã đóng cửa / Ngừng hoạt động'), ('WRONG_INFO', 'Sai lệch thông tin (Địa chỉ, số điện thoại, giá)'), ('SPAM', 'Nội dung spam, quảng cáo rác hoặc trùng lặp'), ('OTHER', 'Vấn đề khác')], default='WRONG_INFO', max_length=30, verbose_name='Loại phản ánh')),
                ('description', models.TextField(blank=True, default='', verbose_name='Chi tiết phản ánh')),
                ('status', models.CharField(choices=[('PENDING', 'Đang xử lý'), ('RESOLVED', 'Đã xác minh và cập nhật'), ('DISMISSED', 'Bác bỏ / Không chính xác')], db_index=True, default='PENDING', max_length=20, verbose_name='Trạng thái xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian báo cáo')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='places.place', verbose_name='Địa điểm bị báo cáo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_reports', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo')),
            ],
            options={
                'verbose_name': 'Báo cáo sai lệch địa điểm',
                'verbose_name_plural': 'Danh sách báo cáo địa điểm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm lưu')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='places.place', verbose_name='Địa điểm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Địa điểm đã lưu',
                'verbose_name_plural': 'Danh sách địa điểm đã lưu',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'place'), name='unique_user_saved_place')],
            },
        ),
    ]
