# Generated by Django 6.1.1 on 2026-09-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_data_source_place_district_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Danh sách link ảnh album (Google Maps)'),
        ),
    ]
