# Generated by Django 6.1.1 on 2026-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_rejected_reason',
            field=models.TextField(blank=True, default='', verbose_name='Lý do từ chối xác thực'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Chưa gửi xác thực'), ('pending', 'Đang chờ xác minh'), ('verified', 'Đã xác thực cư dân'), ('rejected', 'Bị từ chối xác thực')], db_index=True, default='unverified', max_length=20, verbose_name='Trạng thái xác thực'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xác nhận local'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residing_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Thời gian cư trú tự khai (tháng)'),
        ),
    ]
