# Generated by Django 6.1.1 on 2026-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_verification_rejected_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_verification_modal',
            field=models.BooleanField(default=False, verbose_name='Đã xem pop-up chúc mừng xác thực'),
        ),
    ]
