# Generated by Django 6.1.1 on 2026-09-27 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='FCM Token')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20, verbose_name='Hệ điều hành thiết bị')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Trạng thái kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Device Token FCM',
                'verbose_name_plural': 'Danh sách Device Tokens',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung thông báo')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu kèm theo (Payload)')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian gửi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Hộp thư thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
